### ISSUE TITLE
30px margin on individual element can mess with layout

### ISSUE THREAD

**Issue by indykoning** [KTibow/lovelace-light-soft-ui-theme#5]
First of all thank you so much for baking the soft-ui into a theme, when i first saw it come out i wanted it but it was too much work editing every card, and wouldn't work for me having a random theme every time it turns day or night. Seeing card-mod brought theme support i got excited and lo and behold!

Placing a 30px margin around every card in home assistant causes an issue in my setup though:
![page_1](https://user-images.githubusercontent.com/15870933/88977439-34d1b800-d2be-11ea-8557-916cf96cd5ae.png)
The buttons for the entity cards in the horizontal rows are a bit messed up, but can be fixed by overwriting the margins
![page_2](https://user-images.githubusercontent.com/15870933/88977235-d73d6b80-d2bd-11ea-86ad-74b1a0dfd952.png)
and the spacing between all cards seem a bit odd.

If i remove the 30px margin on every individual card and rather add
```
    #columns > .column {
      margin: 0 30px;
    }
```
to place the margin on the columns, i get this which looks a lot prettier and i hope gets the same effect.

![page_1_fix](https://user-images.githubusercontent.com/15870933/88977668-a3167a80-d2be-11ea-83c4-08f0237eca1c.png)
![page_2_fix](https://user-images.githubusercontent.com/15870933/88977683-a578d480-d2be-11ea-88ef-b9b05f1b8100.png)
the type-entities card seems a little off in the 2nd picture though.

Maybe you could have a look if it is possible to apply the 30px styling this way.
if not that's fine as well, either way great theme!

**Comment by KTibow** [comment]
Hmm. What about `10px 0` per card and `0 20px` per column? That way it would still work well.

**Comment by KTibow** [comment]
By the way, I think this would be a slightly better custom header config:
```yaml
custom_header:
  active_tab_color: var(--sidebar-selected-icon-color)
  background: var(--primary-background-color)
  compact_mode: true
  elements_color: var(--primary-text-color)
  notification_dot_color: var(--sidebar-selected-icon-color)
  tab_indicator_color: var(--sidebar-selected-icon-color)
```
