### ISSUE TITLE
card-mod making theme not aligned

### ISSUE THREAD

**Issue by mrocha-montes** [KTibow/lovelace-light-soft-ui-theme#6]
Without card-mod
![PrtScr capture](https://user-images.githubusercontent.com/55386902/89400145-d9eaf700-d6e9-11ea-82c4-14c22dc18695.jpg)

With card-mod
![PrtScr capture_2](https://user-images.githubusercontent.com/55386902/89400162-e2433200-d6e9-11ea-8410-6535ccc84c83.jpg)

**Comment by KTibow** [comment]
This is an intentional part of the theme. You can always modify it, but it'll get erased in any update. Here's the part that does that:
```css
    #columns {
      flex-direction: column !important;
      margin: 0 auto;
      max-width: 500px;
    }
```
I applied this effect because it's shown that way in the official repo:
![screen](https://github.com/N-l1/lovelace-soft-ui/blob/master/docs/images/soft_ui_light.jpg?raw=1)
